"""adding type now in watchlist

Revision ID: 645703b15baa
Revises: c09b17e8c0fa
Create Date: 2025-03-21 16:08:16.151518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645703b15baa'
down_revision: Union[str, None] = 'c09b17e8c0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlists', 'type')
    # ### end Alembic commands ###
