"""adding user alert table

Revision ID: a8938c2210e3
Revises: c68172241c8f
Create Date: 2025-03-15 06:48:37.357982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8938c2210e3'
down_revision: Union[str, None] = 'c68172241c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_alerts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_alerts')
    # ### end Alembic commands ###
