"""adding google auth

Revision ID: c09b17e8c0fa
Revises: a8938c2210e3
Create Date: 2025-03-15 14:43:04.225161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09b17e8c0fa'
down_revision: Union[str, None] = 'a8938c2210e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('social_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_provider')
    op.drop_column('users', 'social_id')
    # ### end Alembic commands ###
